AllCops:
  TargetRubyVersion: 3.1

Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: true
  Max: 10
  CountAsOne:
    - array
    - hash
    - method_call
